# Generated by Django 4.2.4 on 2023-09-15 16:37

from django.db import migrations, models
import django.db.models.deletion
import producto.models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=30)),
                ('porcentaje_iva', models.DecimalField(decimal_places=1, help_text='Porcentaje del iva ej = 16 - 19 ...', max_digits=3)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Valor del producto antes de iva', max_digits=10)),
                ('stock', models.IntegerField(help_text='Cantidad del producto en inventario')),
                ('oferta', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('proveedor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.proveedor')),
                ('subcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.subcategoria')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, default='imagen/productos/404.png', help_text='Imagen del producto', null=True, upload_to=producto.models.nombreImagen)),
                ('color', models.CharField(max_length=26)),
                ('stock', models.IntegerField(blank=True, help_text='Cantidad del producto del color agg', null=True)),
                ('producto_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto')),
            ],
            options={
                'db_table': 'color',
            },
        ),
    ]
