# Generated by Django 4.2.4 on 2023-09-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=1, help_text='Texto descriptivo del producto', max_length=500),
            preserve_default=False,
        ),
    ]
