# Generated by Django 4.2.4 on 2023-09-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='proveedor_id',
            new_name='proveedor',
        ),
    ]
