# Generated by Django 4.2.4 on 2023-09-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_producto_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
