# Generated by Django 4.2.4 on 2023-09-17 20:32

from django.db import migrations, models
import producto.models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_alter_categoria_imagen_alter_color_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(help_text='Imagen de la categoria', upload_to=producto.models.nombreImagen),
        ),
        migrations.AlterField(
            model_name='color',
            name='imagen',
            field=models.ImageField(help_text='Imagen del producto', upload_to=producto.models.nombreImagen),
        ),
    ]
