# Generated by Django 4.2.4 on 2023-09-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_clientes_casa_apto_clientes_ciudad_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
    ]
