# Generated by Django 4.2.4 on 2023-09-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_rename_clientes_cliente_alter_cliente_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
