# Generated by Django 4.2.4 on 2023-09-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='hola',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
