# Generated by Django 4.2.4 on 2023-09-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_alter_cliente_hola'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='hola',
            new_name='user',
        ),
    ]
