# Generated by Django 4.2.4 on 2023-09-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_rename_hola_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
    ]
