# Generated by Django 4.2.4 on 2023-11-17 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0008_alter_categoria_imagen_alter_color_imagen'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del metodo de pago', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('estado', models.CharField(help_text='Estado del pedido', max_length=30)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente')),
                ('metodo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factura.metodospago')),
            ],
            options={
                'db_table': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad del producto')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factura.factura')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto')),
            ],
            options={
                'db_table': 'Detalle_factura',
            },
        ),
    ]
