# Generated by Django 4.2.4 on 2023-11-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_cliente_user'),
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField()),
                ('situacion', models.CharField(help_text='Si el pedido se encuentra en ruta, entregado o no ha sido enviado', max_length=60)),
                ('productos', models.FileField(blank=True, null=True, upload_to='')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factura.metodospago')),
            ],
        ),
    ]
