# Generated by Django 4.2.4 on 2023-11-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_cliente_user'),
        ('factura', '0002_pedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Pedidos',
        ),
        migrations.AlterModelTable(
            name='pedidos',
            table='Pedidos',
        ),
    ]
