# Generated by Django 4.2.4 on 2023-11-19 04:25

from django.db import migrations, models
import django.db.models.deletion
import factura.models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_rename_pedido_pedidos_alter_pedidos_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factura.pedidos'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_factura',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='productos',
            field=models.FileField(blank=True, null=True, upload_to=factura.models.nombreImagen),
        ),
    ]
